### ISSUE TITLE
Isolation Testing

### ISSUE THREAD

**Issue by pkopicar** [pkopicar/normex#1]
Toto skusam len tak zo srandy ze ako by to fungovalo

**Comment by pkopicar** [comment]
V JIRE nieje presne oznaceny build s ktorym testovat.

**Comment by pkopicar** [comment]
Merge moze byt blokovany necinnostou QA. Toto moze byt problem hlavne ak niekto caka na fix niekoho ineho v hlavnom branchi

**Comment by dudasl** [comment]
Merge by nemal byt blokovaný nečinnosťou QA, pretože ak bude mať niečo vyššiu prioritu, tak sa predsa QA bude venovať tomu.

**Comment by mato7d5** [comment]
isolation preberate takto verejne? :) vidi to hocikto, toto nie je private repo :)

**Comment by pkopicar** [comment]
ja viem, tam som len skusal ci a ako na githube funguje threaded konverzacia, z coho nakoniec vyskytlo ze nijak…
